# base image
FROM debian:trixie-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN rm -f /etc/apt/apt.conf.d/docker-clean

# install apt packages and dependencies
RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    sudo git make curl gnupg2 wget ca-certificates openssh-client \
    # c++
    build-essential clang clang-tidy clang-format cmake gdb \
    # vcpkg
    curl zip unzip tar pkg-config

ARG USERNAME=devcontainer
ARG USER_UID=1000
ARG USER_GID=1000
# add $USER to usergroup
RUN groupadd --gid ${USER_GID} ${USERNAME} &&\
    useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} -s /bin/bash

# locale and timezone
ENV TZ="Etc/UTC"
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

USER ${USERNAME}

# install vcpkg (non-root)
# renovate: datasource=github-tags depName=microsoft/vcpkg versioning=loose
ARG VCPKG_VERSION=2026.05.25
RUN --mount=type=bind,source=scripts/install_vcpkg.sh,target=/tmp/install_vcpkg.sh,readonly \
    VCPKG_VERSION=${VCPKG_VERSION} /tmp/install_vcpkg.sh /home/${USERNAME}

ENV PATH="$PATH:/home/${USERNAME}/vcpkg/"
ENV VCPKG_ROOT=/home/${USERNAME}/vcpkg/


# working directory
ARG REPOSITORY_NAME=cpp_devcontainer
WORKDIR /${REPOSITORY_NAME}

# entry point
ENTRYPOINT ["/bin/bash"]